name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Optional: allow manual trigger

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Grant permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 5. Lint check
      - name: Run Android Lint
        run: ./gradlew lintDebug

      # 6. Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 7. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
